### ISSUE TITLE
Broken Logout

### ISSUE THREAD

**Issue by kabute** [Nitro/kubernetes-dashboard-iam-proxy#2]
**Issue:**
When clicking on the 'logout' dropdown on the Kubernetes dashboard shows its default login screen (provide token or kubeconfig) rather than going back to the kubernetes-dashboard-iam-proxy login screen. Reloading the site shows the correct UI.

**Expected Behaviour:**
When clicking on the 'logout' dropdown on the Kubernetes dashboard it logs out and shows the kubernetes-dashboard-iam-proxy login screen.

**Comment by dhaven** [comment]
fixed by https://github.com/Nitro/kubernetes-dashboard-iam-proxy/pull/12
